jwt:
  header: Authorization
  secret: ${secretJwt}
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

scheduler:
  reset-day-score: 0 0 12 * * ?

origins: http://localhost:8081